[env:waveshare_esp32s3_usb_msc]
platform = espressif32@6.3.2
board = esp32-s3-r8-opi
board_dir = boards
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
build_src_filter = +<*>
build_flags =
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -I${PROJECT_SRC_DIR}
lib_deps =
