[env:waveshare_esp32s3_usb_msc]
platform = espressif32@6.3.2
board = esp32-s3-r8-opi
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_src_filter = +<*>
board_upload.flash_size = 8MB
board_build.partitions = partitions.csv
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -I${PROJECT_SRC_DIR}
lib_deps =
    lovyan03/LovyanGFX@^1.1.16
