[env:launcher]
platform = espressif32@6.3.2
board = esp32-s3-r8-opi
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_upload.flash_size = 8MB
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
# Custom partition table (shared with the Catchphrase project root)
board_build.partitions = ../partitions.csv
# Flash the factory partition at 0x10000
upload_port = /dev/cu.usbmodem*
lib_deps =
    lovyan03/LovyanGFX@^1.1.16
