[env:launcher]
platform = espressif32@6.3.2
board = esp32-s3-r8-opi
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_upload.flash_size = 16MB
board_dir = boards
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
# Custom partition table (shared with the Catchphrase project root)
board_build.partitions = ../partitions.csv
lib_deps =
